# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Microservices/CartAPI/*
    - Microservices/CartAPI-Deployment-yaml

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'cartapi'
  containerRegistry: 'onlineshopping22acr.azurecr.io'
  dockerfilePath: 'CartAPI/Dockerfile'
  tag: '$(Build.BuildId)'
  deploymentFile: 'CartAPI-Deployment-yaml'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  SNYK_TOKEN: 'f511b604-bdaf-49a2-ab7e-323480977739'
  

stages:

- stage: SecurityScan
  displayName: Scan for security Vulnurabilities
  jobs:  
  - job: SecurityScan
    displayName: SecurityScan
    steps:
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'AZDevOpsSnykServiceConnection'
        testType: 'app'
        targetFile: 'CartAPI/project.assets.json'
        monitorWhen: 'always'
        failOnIssues: true


- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'

       
    - script: |
        curl -Lo ./snyk-to-html.exe "https://static.snyk.io/snyk-to-html/latest/snyk-to-html-win.exe"
        chmod +x snyk-to-html.exe
        ls -la
      displayName: 'Snyk to html install'
  # DO YOUR SCANNING HERE WITH SNYK
  # create variable in Pipelines called 'SNYK_TOKEN' and securely save your Snyk token value
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
    - script: |
        snyk.exe auth $(SNYK_TOKEN)
        snyk.exe test --json | snyk-to-html.exe -o results.html
        ls -la
        cd
      displayName: 'Snyk test'

  # CELEBRATE
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: 'results.html'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'


    - publish: $(System.DefaultWorkingDirectory)/results.html
      artifact: Results.html
